indent_select_categories:
  type: list
  list_type: category
  default: ""
  description:
    en: "Categories or subcategories to nest."

categories_not_indented:
  type: list
  list_type: category
  default: ""
  description:
    en: "Categories not indented if using the setting above."
    
